package yaremchuken.quizknight.entity

enum class QuizType {
    WORD_TRANSLATION_INPUT,
    CHOOSE_CORRECT_OPTION,
    ASSEMBLE_TRANSLATION_STRING,
    WRITE_LISTENED_PHRASE,
    INPUT_LISTENED_WORD_IN_STRING
}